apiVersion: v1
kind: Service
metadata:
  name: ldap
  labels:
    app: ldap
spec:
  ports:
  - port: 389
    targetPort: 389
  selector:
    app: ldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap
spec:
  selector:
    matchLabels:
      app: ldap
  replicas: 1
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: dcm4che/slapd-dcm4chee:2.4.44-15.0
        imagePullPolicy: Always
        ports:
        - containerPort: 389
        envFrom:
        - configMapRef:
            name: kubeunige
