apiVersion: v1
kind: Service
metadata:
  name: pacsldap
  labels:
    app: pacsldap
spec:
  ports:
  - port: 389
    targetPort: 389
  selector:
    app: pacsldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacsldap
spec:
  selector:
    matchLabels:
      app: pacsldap
  replicas: 1
  template:
    metadata:
      labels:
        app: pacsldap
    spec:
      containers:
      - name: pacsldap
        image: dcm4che/slapd-dcm4chee:2.4.44-15.0
        imagePullPolicy: Always
        ports:
        - containerPort: 389
        envFrom:
        - configMapRef:
            name: kubeunige
