apiVersion: v1
kind: Secret
metadata:
  name: kheops.secrets
type: Opaque
stringData:
  kheops_authdb_pass: >
    mypwd
  kheops_pacsdb_pass: >
    Password1!
  kheops_superuser_hmasecret: >
    P47dnfP28ptS/uzuuvEACmPYdMiOtFNLXiWTIwNNPgUjrvTgF/JCh3qZi47sIcpeZaUXw132mfmR4q5K/fwepA==
  kheops_auth_hmasecret: >
    P47dnfP28ptS/uzuuvEACmPYdMiOtFNLXiWTIwNNPgUjrvTgF/JCh3qZi47sIcpeZaUXw132mfmR4q5K/fwepA==
  kheops_keycloak_clientsecret: >
    b227ef2b-f4d9-4c8b-a25c-2005cd083ebf
  kheops_client_dicomwebproxysecret: >
    dicomwebproxyclientpassword
  kheops_client_zippersecret: >
    zipperclientpassword
  kheops_auth_hmasecret_post: >
    P47dnfP28ptS/uzuuvEACmPYdMiOtFNLXiWTIwNNPgUjrvTgF/JCh3qZi47sIcpeZaUXw132mfmR4q5K/fwepA==
  kheops_metric_ressource_password: >
    12345678
  privkey1.pem: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDXbXVEBD/0LDKs
    RqFvLPnZxSbMjM8WhuH8I/D48/2DmMcIw6LcBEs020FowWAzGL+xvICcwSmJogXM
    7F90JWAdClFYlfJEjcLrVzLoZerta9YGNC+JYPB1aMzVxAEufnzRi6P8hVaJaZh9
    x8vmeTbyEqpP8hYMOhwc+6vUlzgk/tjHx+lYTqQTOeX0azWrmHq532ob8QvhN7bl
    rv8k31qN3o5VvJwG1yvHJ1bXMLYKlxYoOxPeiobtXlyAxV6VHXwgI72YSdhK+7Mt
    DcuZMAeeGNJ/x4PfkEPdK+CR8FV+2EKehu8R9eGLIUhGcgE4aZZdi8IO2Opc3u95
    lEU/9TnNAgMBAAECggEALsxzhhQaRJP5ah1p4nn1yQ4gMJ2CO1WP8DNqnNp8P0NI
    Mao2Te+M2u2qlvQzTsZYlmbp1aPMvz54Xh0XW2bnK0fbhhAE8kmNh4yI3Z2OXIdp
    li1uCj0J36eln+aVjyEhQnBAbpIUy4MqAmEN9YJtokbVwspHad6RzuYJXQSAyOBB
    5R7hnEpdpj/mE8YjIiq2q2Dsbi1SBW4phZyJJU3I/AoMx5+HiXix87YgONkoQcUl
    4TWrTOHL+fo0hb2IKB2ZHjUZY6sCv5qWCnth8Z4NRwjNAPTc/Xp+k/EH8LeNK0YM
    IpYbMYrTlBCui4ronj6T6uvrycqt3phOaRPsZqgAzQKBgQDzPTUshw+jUdfojrVO
    mg/Zzwr8VVu2nfYPG0LgexkXTYM6SSLswT2QESrJoBgmtvtNSWw8OOQqTcBBerGB
    QAg7TH1GvlA0iGUwv9I/F2T1tcqBvYXbRJOiI879DapI5ijqT67TPaB/4kfQKDwf
    EEW8xtIZatCAaj1I95VruQSBywKBgQDiursusKDgV42I4l8EwAuNsZEOZqhRWOcV
    m09tC++K6Pwjc5wXXZ5wBuaraAQqy1tYjXf3KI1VmMymc6w43RSDBPyxIhKyuj0T
    qRpPzVU0TdzssnilfQ6l401kFm9WG3DxQ35eL9J1FNKW4UgYecDzJjN4KxUGXMEH
    GLV6Mp5fxwKBgQDLcsanF9DcqfgNbE/6DqJza9mkdUDg3f6RZBvr5wp1kz/P4Jx1
    qqvzdGh1fJK2zxYi7ua4+FzfhWjpW9ZcZVJ9Rt0B7uznA66ft9IDM24elo9rNTpg
    zFsvowPeZS+pCdnvIfb4ePNmA75NPVoMIXAzFZll6RG8VyArh+pSz84VQQKBgQDN
    JEkykIuvEGi2HqP8Z0rM1Im7rvTCTZ8gNJsjvjXpyK5B4Vus5H7zO7tAAWgr1D19
    HNsbnOxsM0mPnX+JH7dsaHm+R2cFoW6buFhfNhjOr1iiLUTt7v3u6H/gfFAWZ9PD
    596Rl9FjMAjujT0vMBJ9reXJ56kpTYk1Q40H2H7lhwKBgBWairtn+dlYVrI0jE02
    hQGG0jXgNJwRHQ8pxbes1lFxykECXpgn+GxtCGyrlt4pq/hYs4MnCRrGOZA+xGxg
    sUrXmiH4y7mTkZELJ0bUFQaDQ7JCAmw+3FiRnD8hahfxCwj07L2HtRuRY3mLCITG
    RhYqfsEf1hNeqeS6juv7cA+0
    -----END PRIVATE KEY-----
  fullchain1.pem: |
    -----BEGIN CERTIFICATE-----
    MIIGETCCBPmgAwIBAgISA1iP6pTlTcS9a0KvfUkXf4tbMA0GCSqGSIb3DQEBCwUA
    MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
    ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xODA1MjgxMDUxMTVaFw0x
    ODA4MjYxMDUxMTVaMB0xGzAZBgNVBAMTEnRlc3Qua2hlb3BzLm9ubGluZTCCASIw
    DQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBANdtdUQEP/QsMqxGoW8s+dnFJsyM
    zxaG4fwj8Pjz/YOYxwjDotwESzTbQWjBYDMYv7G8gJzBKYmiBczsX3QlYB0KUViV
    8kSNwutXMuhl6u1r1gY0L4lg8HVozNXEAS5+fNGLo/yFVolpmH3Hy+Z5NvISqk/y
    Fgw6HBz7q9SXOCT+2MfH6VhOpBM55fRrNauYernfahvxC+E3tuWu/yTfWo3ejlW8
    nAbXK8cnVtcwtgqXFig7E96Khu1eXIDFXpUdfCAjvZhJ2Er7sy0Ny5kwB54Y0n/H
    g9+QQ90r4JHwVX7YQp6G7xH14YshSEZyAThpll2Lwg7Y6lze73mURT/1Oc0CAwEA
    AaOCAxwwggMYMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYI
    KwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQUn1bPgFvmZMsgwa5vN+XY
    +R53ZgowHwYDVR0jBBgwFoAUqEpqYwR93brm0Tm3pkVl7/Oo7KEwbwYIKwYBBQUH
    AQEEYzBhMC4GCCsGAQUFBzABhiJodHRwOi8vb2NzcC5pbnQteDMubGV0c2VuY3J5
    cHQub3JnMC8GCCsGAQUFBzAChiNodHRwOi8vY2VydC5pbnQteDMubGV0c2VuY3J5
    cHQub3JnLzAdBgNVHREEFjAUghJ0ZXN0LmtoZW9wcy5vbmxpbmUwgf4GA1UdIASB
    9jCB8zAIBgZngQwBAgEwgeYGCysGAQQBgt8TAQEBMIHWMCYGCCsGAQUFBwIBFhpo
    dHRwOi8vY3BzLmxldHNlbmNyeXB0Lm9yZzCBqwYIKwYBBQUHAgIwgZ4MgZtUaGlz
    IENlcnRpZmljYXRlIG1heSBvbmx5IGJlIHJlbGllZCB1cG9uIGJ5IFJlbHlpbmcg
    UGFydGllcyBhbmQgb25seSBpbiBhY2NvcmRhbmNlIHdpdGggdGhlIENlcnRpZmlj
    YXRlIFBvbGljeSBmb3VuZCBhdCBodHRwczovL2xldHNlbmNyeXB0Lm9yZy9yZXBv
    c2l0b3J5LzCCAQYGCisGAQQB1nkCBAIEgfcEgfQA8gB3ANt0r+7LKeyx/so+cW0s
    5bmquzb3hHGDx12dTze2H79kAAABY6aWku0AAAQDAEgwRgIhAIZKs9gtKYTKNPka
    /UDZsgbRXcwEZu2g8LfJO1AKY68dAiEAyUpN/xsv49e6/pzqMYsWG0Yy/JWAVTqu
    JIQU/kCZuDQAdwApPFGWVMg5ZbqqUPxYB9S3b79Yeily3KTDDPTlRUf0eAAAAWOm
    lpMIAAAEAwBIMEYCIQDIyKomMdbQiDlTeRDotGYc2ZXeGlD2+xIJVqty+Z7lVwIh
    AORBwKdmmHwcmTy6jA1EE6OZmqf36ZlB/yPSDSNmFhPbMA0GCSqGSIb3DQEBCwUA
    A4IBAQAZsajIqHYAKQtf8mCqcJSAibs6F1wqSLY34z6ZHPKtt2U+IHdFOzRWhIsn
    RzG2OsxhMSKDIWMb8PD9Zb++592Y8qa/GuAUIU5e1AnSmGS8PTTQ0j5WewMRxigj
    N2a3IqpaRPYFQ3FDV18OpnefyURabj4J7Bd6x/QmpGZXxqdoJaislm1AiZn1zpal
    uAT+mD++jYsix4WMKKzf4kxscUD2iW8DgWduTJiT1ubshGue4g8GYvwiNSAUmoiL
    gpLuCe45YZqpAfvKZJDlV39UdX8WPLh6+K3jzlTv2Of7YgFq73mZcZkolPulvCsq
    5A7UrJSyLX+ZGlRtCfyl4NJau38Q
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIEkjCCA3qgAwIBAgIQCgFBQgAAAVOFc2oLheynCDANBgkqhkiG9w0BAQsFADA/
    MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
    DkRTVCBSb290IENBIFgzMB4XDTE2MDMxNzE2NDA0NloXDTIxMDMxNzE2NDA0Nlow
    SjELMAkGA1UEBhMCVVMxFjAUBgNVBAoTDUxldCdzIEVuY3J5cHQxIzAhBgNVBAMT
    GkxldCdzIEVuY3J5cHQgQXV0aG9yaXR5IFgzMIIBIjANBgkqhkiG9w0BAQEFAAOC
    AQ8AMIIBCgKCAQEAnNMM8FrlLke3cl03g7NoYzDq1zUmGSXhvb418XCSL7e4S0EF
    q6meNQhY7LEqxGiHC6PjdeTm86dicbp5gWAf15Gan/PQeGdxyGkOlZHP/uaZ6WA8
    SMx+yk13EiSdRxta67nsHjcAHJyse6cF6s5K671B5TaYucv9bTyWaN8jKkKQDIZ0
    Z8h/pZq4UmEUEz9l6YKHy9v6Dlb2honzhT+Xhq+w3Brvaw2VFn3EK6BlspkENnWA
    a6xK8xuQSXgvopZPKiAlKQTGdMDQMc2PMTiVFrqoM7hD8bEfwzB/onkxEz0tNvjj
    /PIzark5McWvxI0NHWQWM6r6hCm21AvA2H3DkwIDAQABo4IBfTCCAXkwEgYDVR0T
    AQH/BAgwBgEB/wIBADAOBgNVHQ8BAf8EBAMCAYYwfwYIKwYBBQUHAQEEczBxMDIG
    CCsGAQUFBzABhiZodHRwOi8vaXNyZy50cnVzdGlkLm9jc3AuaWRlbnRydXN0LmNv
    bTA7BggrBgEFBQcwAoYvaHR0cDovL2FwcHMuaWRlbnRydXN0LmNvbS9yb290cy9k
    c3Ryb290Y2F4My5wN2MwHwYDVR0jBBgwFoAUxKexpHsscfrb4UuQdf/EFWCFiRAw
    VAYDVR0gBE0wSzAIBgZngQwBAgEwPwYLKwYBBAGC3xMBAQEwMDAuBggrBgEFBQcC
    ARYiaHR0cDovL2Nwcy5yb290LXgxLmxldHNlbmNyeXB0Lm9yZzA8BgNVHR8ENTAz
    MDGgL6AthitodHRwOi8vY3JsLmlkZW50cnVzdC5jb20vRFNUUk9PVENBWDNDUkwu
    Y3JsMB0GA1UdDgQWBBSoSmpjBH3duubRObemRWXv86jsoTANBgkqhkiG9w0BAQsF
    AAOCAQEA3TPXEfNjWDjdGBX7CVW+dla5cEilaUcne8IkCJLxWh9KEik3JHRRHGJo
    uM2VcGfl96S8TihRzZvoroed6ti6WqEBmtzw3Wodatg+VyOeph4EYpr/1wXKtx8/
    wApIvJSwtmVi4MFU5aMqrSDE6ea73Mj2tcMyo5jMd6jmeWUHK8so/joWUoHOUgwu
    X4Po1QYz+3dszkDqMp4fklxBwXRsW10KXzPMTZ+sOPAveyxindmjkW8lGy+QsRlG
    PfZ+G6Z6h7mjem0Y+iWlkYcV4PIWL1iwBi8saCbGS5jN2p8M+X+Q7UNKEkROb3N6
    KOqkqm57TH2H3eDJAkSnh6/DNFu0Qg==
    -----END CERTIFICATE-----
