version: "3.1"
services:
  nginx:
    image: osirixfoundation/kheops-keycloak-nginx:${KHEOPS_KEYCLOAK_NGINX}
    container_name: keycloak-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - keycloak

  keycloak:
    image: jboss/keycloak:${KEYCLOAK_TAG}
    container_name: keycloak
    env_file: docker-compose.env
    volumes:
      - keycloak-standalone:/opt/keycloak/standalone
      - ./themes/kheops:/opt/jboss/keycloak/themes/kheops:ro
      - ./themes/medirad:/opt/jboss/keycloak/themes/medirad:ro
      - ./themes/lavim:/opt/jboss/keycloak/themes/lavim:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
    extra_hosts:
      - "smtp.unige.ch:10.194.9.231"
      - "smtp.unige.ch:10.194.9.232"
    secrets:
      - psql_password

secrets:
  psql_password:
    file: secrets/psql_password

volumes:
  keycloak-standalone:
  letsencrypt:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"
