---
    version: "3.1"
    services:
      postgres:
        image: postgres:${POSTGRES_TAG}
        container_name: keycloak-psql
        env_file: docker-compose.env
        volumes:
          - postgres_data:/var/lib/postgresql/data
        secrets:
          - psql_password
        restart: unless-stopped

      nginx:
        image: osirixfoundation/kheops-keycloak-nginx:${KHEOPS_KEYCLOAK_NGINX}
        container_name: keycloak-nginx
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - letsencrypt:/etc/letsencrypt
        depends_on:
          - postgres
          - keycloak
        restart: unless-stopped
    
      keycloak:
        image: jboss/keycloak:${KEYCLOAK_TAG}
        container_name: keycloak
        env_file: docker-compose.env
        depends_on:
          - postgres
        volumes:
          - keycloak-standalone:/opt/keycloak/standalone
          - ./themes/kheops:/opt/jboss/keycloak/themes/kheops:ro
          - ./themes/medirad:/opt/jboss/keycloak/themes/medirad:ro
          - ./themes/lavim:/opt/jboss/keycloak/themes/lavim:ro
        logging:
          driver: json-file
          options:
            max-size: "10m"
        extra_hosts:
          - "smtp.unige.ch:10.194.9.231"
          - "smtp.unige.ch:10.194.9.232"
        secrets:
          - psql_password
        restart: unless-stopped

    secrets:
      psql_password:
        file: secrets/psql_password
    
    volumes:
      keycloak-standalone:
      postgres_data:
      letsencrypt:

    
