apiVersion: v1
kind: Service
metadata:
  name: kheopsdicomwebproxy
  labels:
    app: kheopsdicomwebproxy
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kheopsdicomwebproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopsdicomwebproxy
spec:
  selector:
    matchLabels:
      app: kheopsdicomwebproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopsdicomwebproxy
    spec:
      containers:
      - name: kheopsdicomwebproxy
        image: osirixfoundation/kheops-dicomweb-proxy:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kubeunige
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/kheops_auth_hmasecret_post"
          subPath: kheops_auth_hmasecret_post
        - name: secrets
          mountPath: "/run/secrets/kheops_client_dicomwebproxysecret"
          subPath: kheops_client_dicomwebproxysecret
      volumes:
      - name: secrets
        secret:
          secretName: kheops.secrets
          items:
          - key: kheops_auth_hmasecret_post
            path: kheops_auth_hmasecret_post
          - key: kheops_client_dicomwebproxysecret
            path: kheops_client_dicomwebproxysecret
