version: '3.1'
services:
  ohif:
    container_name: ohif
    image: osirixfoundation/viewer:latest
    restart: on-failure
    environment:
      - SERVER_NAME=ohif.kheops.online
    ports:
      - "80:80"
      - "443:443"
    secrets:
      - privkey1.pem
      - fullchain1.pem
secrets:
  privkey1.pem:
    file: secrets/privkey1.pem
  fullchain1.pem:
    file: secrets/fullchain1.pem
