apiVersion: v1
kind: Service
metadata:
  name: kheopsui
  labels:
    app: kheopsui
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: kheopsui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopsui
spec:
  selector:
    matchLabels:
      app: kheopsui
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopsui
    spec:
      containers:
      - name: kheopsui
        image: osirixfoundation/kheops-ui:master
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: kubeunige
