apiVersion: v1
kind: Service
metadata:
  name: kheopszipper
  labels:
    app: kheopszipper
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: kheopszipper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kheopszipper
spec:
  selector:
    matchLabels:
      app: kheopszipper
  replicas: 1
  template:
    metadata:
      labels:
        app: kheopszipper
    spec:
      containers:
      - name: kheopszipper
        image: osirixfoundation/kheops-zipper:master
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: kubeunige
        volumeMounts:
        - name: secrets
          mountPath: "/run/secrets/kheops_client_zippersecret"
          subPath: kheops_client_zippersecret
      volumes:
      - name: secrets
        secret:
          secretName: kheops.secrets
          items:
          - key: kheops_client_zippersecret
            path: kheops_client_zippersecret
