version: '3.7'

x-environment:
  - &oidc-provider KHEOPS_OIDC_PROVIDER=https://keycloak.kheops.online/auth/realms/${INSTANCE_NAME:?err}
  - &root-url KHEOPS_ROOT_URL=https://${INSTANCE_NAME:?err}.kheops.online

services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:2.4.48-22.1
    environment:
      - STORAGE_DIR=/storage/fs1
    volumes:
      - dcm4chee-ldap-ldap:/var/lib/openldap/openldap-data
      - dcm4chee-ldap-slapdd:/etc/openldap/slapd.d
    networks:
      - pacs_network

  arc:
    container_name: kheopspacsarc
    build:
      context: ./kheops-dcm4chee-arc-psql
    environment:
      - WILDFLY_CHOWN=/opt/wildfly/standalone
      - WILDFLY_WAIT_FOR=ldap:389
      - JAVA_OPTS=-Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true
      - POSTGRES_DB=${INSTANCE_NAME:?err}_pacs
      - POSTGRES_USER=${INSTANCE_NAME:?err}_pacs
      - POSTGRES_PASSWORD_FILE=/run/secrets/kheops_pacsdb_pass
      - POSTGRES_HOST=10.5.6.2
    secrets:
      - kheops_pacsdb_pass
    volumes:
      - dcm4chee-arc-standalone:/opt/wildfly/standalone
      - /medirad12_archive:/storage
    networks:
      - pacs_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v0.9.4-max10
    env_file: docker-compose.env
    environment:
      - *root-url
      - *oidc-provider
      - KHEOPS_WELCOMEBOT_WEBHOOK
      - KHEOPS_AUTHDB_USER=${INSTANCE_NAME:?err}_authorization
      - KHEOPS_AUTHDB_NAME=${INSTANCE_NAME:?err}_authorization
      - KHEOPS_AUTHDB_URL=postgresql://10.5.6.2:5432r
      - KHEOPS_AUTHORIZATION_ENABLE_ELASTIC=true
      - KHEOPS_AUTHORIZATION_ELASTIC_INSTANCE=${INSTANCE_NAME:?err}
      - KHEOPS_AUTHORIZATION_LOGSTASH_URL=kibana.kheops.online:5044
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    networks:
      - kheops_network
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "kibana.kheops.online:10.5.7.8"
      - "reportprovider.kheops.online:10.5.5.33"

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v0.9.4
    env_file: docker-compose.env
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v0.9.4
    env_file: docker-compose.env
    environment:
      - *root-url
      - *oidc-provider
      - KHEOPS_UI_TITLE=Kheops
      - KHEOPS_UI_CLIENTID=loginConnect
      - KHEOPS_UI_USER_MANAGEMENT_URL=https://keycloak.kheops.online/auth/realms/${INSTANCE_NAME:?err}/account
      - KHEOPS_VIEWER_URL=https://ohif.kheops.online
      - KHEOPS_VIEWER_SM_URL=https://reportprovider.kheops.online/wsi-viewer
      - KHEOPS_UI_ENABLE_ELASTIC=false
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v0.9.4
    env_file: docker-compose.env
    environment:
      - *root-url
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network
    extra_hosts:
      - "kibana.kheops.online:10.5.7.8"

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:v0.9.4-letsencrypt
    container_name: kheopsreverseproxy
    environment:
      - *root-url
      - *oidc-provider
      - KHEOPS_REVERSE_PROXY_ENABLE_ELASTIC=true
      - KHEOPS_REVERSE_PROXY_ELASTIC_INSTANCE=${INSTANCE_NAME:?err}
      - KHEOPS_REVERSE_PROXY_LOGSTASH_URL=kibana.kheops.online:5044
    env_file: docker-compose.env
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - kheops-zipper
      - pacs-authorization-proxy
    networks:
      - kheops_network
      - frontend_network
      - reverseproxy_network
    extra_hosts:
      - "${INSTANCE_NAME:?err}.kheops.online:127.0.0.1"
      - "kibana.kheops.online:10.5.7.8"

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    environment:
      - KHEOPS_PEP_ENABLE_ELASTIC=true
      - KHEOPS_PEP_ELASTIC_INSTANCE=${INSTANCE_NAME:?err}
      - KHEOPS_PEP_LOGSTASH_URL=kibana.kheops.online:5044
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v0.9.4
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - kheops_network
      - pacs_network
    extra_hosts:
      - "kibana.kheops.online:10.5.7.8"

secrets:
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_superuser_hmasecret:
    file: secrets/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: secrets/kheops_metric_ressource_password

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-arc-standalone:
  letsencrypt:


networks:
  kheops_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"
  pacs_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.101.0/24"
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.102.0/24"
  reverseproxy_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.103.0/24"

