---
version: "3.1"
services:
# DCM4CHEE uses the an LDAP server for configuration, as per the DICOM 
# Application Configuration Management Profile. For this installation
# we do not apply any custom configuration to DCM4CEE
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.4.48-21.0
    env_file: docker-compose.env
    networks:
      - pacs_network

# DCM4CHEE uses this PostgreSQL database
  pacs-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:12.1-21
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    networks:
      - pacs_network

# The main DCM4CHEE container
  pacs-arc:
    container_name: kheops-pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.21.0
    env_file: docker-compose.env
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
      STORAGE_DIR: /storage/fs1
      POSTGRES_HOST: pacspostgres
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - pacs-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      - pacs_network

# KHEOPS persists all data to this PostgreSQL database
  kheops-postgres:
    container_name: kheopspostgres
    image: postgres:12.1-alpine
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kheops
      POSTGRES_USER: kheopsuser
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    networks:
      - kheops_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v0.9.4
    env_file: docker-compose.env
    environment:
      - JAVA_OPTS=-Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true
    depends_on:
      - kheops-postgres
    secrets:
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "kibana.kheops.online:10.5.5.31"
      - "reportprovider.kheops.online:10.5.5.33"
    networks:
      - kheops_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v0.9.4
    environment:
      - JAVA_OPTS=-Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true
    env_file: docker-compose.env
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v0.9.4
    env_file: docker-compose.env
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v0.9.4
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true
    env_file: docker-compose.env
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:v0.9.4-insecure
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - kheops-ui
      - kheops-zipper
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network
      - frontend_network
      - reverseproxy_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v0.9.4
    depends_on:
      - pacs-arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - pacs_network
      - kheops_network

  irdbb-import:
    container_name: irdbbimport
    image: osirixfoundation/irdbb-import:v1.0.1
    env_file: docker-compose.env
    restart: on-failure
    networks:
      - kheops_network
      - irdbb_importer_network

secrets:
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: secrets/kheops_metric_ressource_password

volumes:
  keycloak-standalone-data:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:
  kheops-db-data:

networks:
  kheops_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"
  pacs_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.101.0/24"
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.102.0/24"
  reverseproxy_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.103.0/24"
  irdbb_importer_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.104.0/24"
