version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:${PACS_LDAP_IMAGE_TAG}
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - dcm4chee-ldap-ldap:/var/lib/ldap
      - dcm4chee-ldap-slapdd:/etc/ldap/slapd.d
    restart: on-failure
    networks:
      - pacs_network

  db:
    container_name: db
    image: osirixfoundation/kheops-database:${KHEOPS_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    env_file: docker-compose.env
    secrets:
      - kheops_authdb_pass
      - kheops_pacsdb_pass
    restart: on-failure
    networks:
      - kheops_network

  arcdb:
    container_name: arcdb
    image: dcm4che/postgres-dcm4chee:${PACS_PSQL_IMAGE_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    restart: always
    networks:
      - pacs_network

  arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:${KHEOPS_ARC_IMAGE_TAG}
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 arcdb:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - arcdb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - /dcm4chee-arc/storage:/storage
    restart: on-failure
    networks:
      - pacs_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=UTC"
    depends_on:
      - db
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "reportprovider.kheops.online:10.5.5.33"
    networks:
      - kheops_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - elastic_cloud_id
      - elastic_cloud_auth
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
      - welcomebot
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - pacs_network
      - kheops_network

  welcomebot:
    container_name: welcomebot
    env_file: docker-compose.env
    image: osirixfoundation/kheops-welcome-bot:${KHEOPS_WELCOME_BOT_IMAGE_TAG}
    restart: on-failure
    secrets:
      - welcomebot_token
    networks:
      - kheops_network

  ohif:
    container_name: ohif
    image: osirixfoundation/viewer:reportprovider
    restart: on-failure
    environment:
      - SERVER_NAME=demo.kheops.online
    networks:
      - kheops_network

secrets:
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: ${SECRETS_PATH}/kheops_pacsdb_pass
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  kheops_keycloak_clientsecret:
    file: ${SECRETS_PATH}/kheops_keycloak_clientsecret
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  welcomebot_token:
    file: ${SECRETS_PATH}/welcomebot_token
  elastic_cloud_id:
    file: ${SECRETS_PATH}/elastic_cloud_id
  elastic_cloud_auth:
    file: ${SECRETS_PATH}/elastic_cloud_auth
  elastic_pwd:
    file: ${SECRETS_PATH}/elastic_pwd
  kheops_metric_ressource_password:
    file: ${SECRETS_PATH}/kheops_metric_ressource_password
volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  kheops-db-data:
  
networks:
  kheops_network:
    driver: bridge
  pacs_network:
    driver: bridge
  frontend_network:
    driver: bridge
