version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:
  auth-db:
    container_name: authdb
    image: postgres:${KHEOPS_AUTHORIZATION_PSQL_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kheops
      - POSTGRES_USER=kheopsuser
      - POSTGRES_PASSWORD_FILE=/run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    restart: on-failure
    
  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - auth-db
      - arc
    environment:
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8089"
    ports:
      - "8089:8089"
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    restart: on-failure
    env_file: docker-compose.env
    ports:
      - "8049:8080"
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    ports:
      - "80:80"
      - "443:443"
      - "8042:8042"
      - "8048:8048"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    ports:
      - "82:80"
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - pacs_network

secrets:
  kheops_pacsdb_pass:
    file: ${SECRETS_PATH}/kheops_pacsdb_pass
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  kheops_keycloak_clientsecret:
    file: ${SECRETS_PATH}/kheops_keycloak_clientsecret
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: ${SECRETS_PATH}/kheops_metric_ressource_password

networks:
  pacs_network:
    external:
      name: pacs_network

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  kheops-db-data:
