version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:${PACS_LDAP_IMAGE_TAG}
    env_file: docker-compose.env
    volumes:
      - dcm4chee-ldap-ldap:/var/lib/ldap
      - dcm4chee-ldap-slapdd:/etc/ldap/slapd.d
    restart: on-failure
    networks:
      - pacs_network

  db:
    container_name: db
    image: osirixfoundation/kheops-database:${KHEOPS_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    env_file: docker-compose.env
    secrets:
      - kheops_authdb_pass
      - kheops_pacsdb_pass
    restart: on-failure
    networks:
      - kheops_network

  arcdb:
    container_name: arcdb
    image: dcm4che/postgres-dcm4chee:${PACS_PSQL_IMAGE_TAG}
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    restart: always
    networks:
      - pacs_network

  arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:${KHEOPS_ARC_IMAGE_TAG}
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 arcdb:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - arcdb
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-data:/storage
    restart: on-failure
    networks:
      - pacs_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    volumes:
      - logs_auth:/usr/local/tomcat/logs
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=UTC"
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8089 -Xms64m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m
 #   ports:
 #     - "8089:8089"
    depends_on:
      - db
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
    extra_hosts:
      - "keycloak.kheops.online:10.5.7.29"
      - "reportprovider.kheops.online:10.5.7.30"
    networks:
      - kheops_network
      - kheops_beat_network
  
  kheops-authorization-metricbeat:
    container_name: kheopsauthorizationmetricbeat
    image: osirixfoundation/kheops-authorization-metricbeat:${KHEOPS_METRICBEAT_SIDECAR_TAG}
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
    networks:
      - kheops_beat_network
      
  kheops-filebeat-sidecar:
    container_name: kheopsfilebeatsidecar
    image: osirixfoundation/kheops-filebeat-sidecar:${KHEOPS_FILEBEAT_SIDECAR_TAG}
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - kheops-reverse-proxy
      - pacs-authorization-proxy
    volumes:
      - logs_auth:/kheops/authorization/logs
      - logs_pep:/kheops/pep/logs
      - logs_reverse_proxy:/kheops/reverseproxy/logs
      - filebeat_registry:/registry
    networks:
      - kheops_beat_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    env_file: docker-compose.env
    restart: on-failure
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network

  kheops-reverse-proxy:
    container_name: kheopsreverseproxy
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    volumes:
      - logs_reverse_proxy:/var/log/nginx
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    env_file: docker-compose.env
    ports:
      - "8081:8042"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
      - welcomebot
      - ohif
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    volumes:
      - logs_pep:/var/log/nginx
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - pacs_network
      - kheops_network

  welcomebot:
    container_name: welcomebot
    env_file: docker-compose.env
    image: osirixfoundation/kheops-welcome-bot:${KHEOPS_WELCOME_BOT_IMAGE_TAG}
    restart: on-failure
    secrets:
      - welcomebot_token
    networks:
      - kheops_network

  ohif:
    container_name: ohif
    image: osirixfoundation/viewer:reportprovider
    restart: on-failure
    environment:
      - SERVER_NAME=demo.kheops.online
    networks:
      - frontend_network

secrets:
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: ${SECRETS_PATH}/kheops_pacsdb_pass
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  welcomebot_token:
    file: ${SECRETS_PATH}/welcomebot_token

volumes:
  dcm4chee-arc-data:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  kheops-db-data:
  logs_pep:
  logs_reverse_proxy:
  logs_auth:
  filebeat_registry:
  
networks:
  kheops_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.241.0/24"
  pacs_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.242.0/24"
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.243.0/24"
  kheops_beat_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.244.0/24"
