version: '3.7'

x-environment:
  - &oidc-provider KHEOPS_OIDC_PROVIDER=https://keycloak.kheops.online/auth/realms/irdbb
  - &root-url KHEOPS_ROOT_URL=https:///medirad-staging.kheops.online

services:
# DCM4CHEE uses the an LDAP server for configuration, as per the DICOM 
# Application Configuration Management Profile. For this installation
# we do not apply any custom configuration to DCM4CEE
  ldap:
    container_name: ldap
    image: dcm4che/slapd-dcm4chee:2.4.48-21.0
    env_file: docker-compose.env
    networks:
      - pacs_network

# DCM4CHEE uses this PostgreSQL database
  pacs-postgres:
    container_name: pacspostgres
    image: dcm4che/postgres-dcm4chee:12.1-21
    logging:
      driver: json-file
      options:
        max-size: "10m"
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
    env_file: docker-compose.env
    volumes:
      - dcm4chee-db-data:/var/lib/postgresql/data
    secrets:
      - kheops_pacsdb_pass
    networks:
      - pacs_network

# The main DCM4CHEE container
  pacs-arc:
    container_name: kheops-pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.21.0
    env_file: docker-compose.env
    environment:
      POSTGRES_DB: kheops_pacs
      POSTGRES_USER: kheops_pacs
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_pacsdb_pass
      STORAGE_DIR: /storage/fs1
      POSTGRES_HOST: pacspostgres
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 pacspostgres:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - pacs-postgres
    volumes:
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-storage:/storage
    networks:
      - pacs_network

# KHEOPS persists all data to this PostgreSQL database
  kheops-postgres:
    container_name: kheopspostgres
    image: postgres:12.1-alpine
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: kheops
      POSTGRES_USER: kheopsuser
      POSTGRES_PASSWORD_FILE: /run/secrets/kheops_authdb_pass
    secrets:
      - kheops_authdb_pass
    networks:
      - kheops_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v0.9.6
    env_file: docker-compose.env
    environment:
      - JAVA_OPTS=-Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true
      - *root-url
      - *oidc-provider
      - KHEOPS_WELCOMEBOT_WEBHOOK
      - KHEOPS_AUTHDB_USER=kheopsuser
      - KHEOPS_AUTHDB_NAME=kheops
      - KHEOPS_AUTHDB_URL=postgresql://10.5.6.2:5432
      - CATALINA_OPTS="-Duser.timezone=UTC"
    depends_on:
      - kheops-postgres
    secrets:
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "reportprovider.kheops.online:10.5.5.33"
    networks:
      - kheops_network
      - kheops_beat_network

  kheops-authorization-metricbeat:
    container_name: kheopsauthorizationmetricbeat
    image: osirixfoundation/kheops-authorization-metricbeat:v0.9.6
    env_file: docker-compose.env
    environment:
      - KHEOPS_INSTANCES=medirad-staging
      - KHEOPS_LOGSTASH_URL=10.5.7.13:5044
    depends_on:
      - kheops-authorization
    networks:
      - kheops_beat_network
      
  kheops-filebeat-sidecar:
    container_name: kheopsfilebeatsidecar
    image: osirixfoundation/kheops-filebeat-sidecar:v0.9.6
    environment:
      - KHEOPS_INSTANCES=medirad-staging
      - KHEOPS_LOGSTASH_URL=10.5.7.13:5044
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization
      - kheops-reverse-proxy
      - pacs-authorization-proxy
    volumes:
      - logs_auth:/kheops/authorization/logs
      - logs_pep:/kheops/pep/logs
      - logs_reverse_proxy:/kheops/reverseproxy/logs
    networks:
      - kheops_beat_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v0.9.6
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    environment:
      - JAVA_OPTS=-Xms64m -Xmx512m -Djava.net.preferIPv4Stack=true
    env_file: docker-compose.env
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v0.9.6
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    env_file: docker-compose.env
    environment:
      - *root-url
      - *oidc-provider
      - KHEOPS_UI_TITLE=Kheops
      - KHEOPS_UI_CLIENTID=irdbb-ui
      - KHEOPS_UI_USER_MANAGEMENT_URL=https://keycloak.kheops.online/auth/realms/irdbb/account
      - KHEOPS_VIEWER_URL=https://ohif.kheops.online
      - KHEOPS_VIEWER_SM_URL=https://reportprovider.kheops.online/wsi-viewer
    networks:
      - frontend_network

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v0.9.6
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    environment:
      - JAVA_OPTS=-Xms512m -Xmx512m -Djava.net.preferIPv4Stack=true
      - *root-url
    env_file: docker-compose.env
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    networks:
      - kheops_network

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:main-insecure
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    volumes:
      - logs_reverse_proxy:/var/log/nginx
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - kheops-ui
      - kheops-zipper
    networks:
      - kheops_network
      - frontend_network
      - reverseproxy_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v0.9.6
    volumes:
      - logs_pep:/var/log/nginx
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "10m"
    depends_on:
      - pacs-arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    networks:
      - pacs_network
      - kheops_network

  irdbb-import:
    container_name: irdbbimport
    image: osirixfoundation/irdbb-import:v1.0.1
    env_file: docker-compose.env
    restart: on-failure
    networks:
      - kheops_network
      - irdbb_importer_network

secrets:
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret

volumes:
  keycloak-standalone-data:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-storage:
  kheops-db-data:
  logs_pep:
  logs_reverse_proxy:
  logs_auth:

networks:
  kheops_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"
  pacs_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.101.0/24"
  frontend_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.102.0/24"
  reverseproxy_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.103.0/24"
  irdbb_importer_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.104.0/24"
  kheops_beat_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.16.105.0/24"
