version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:


  ldap:
    image: dcm4che/slapd-dcm4chee:2.4.44-19.0
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dcm4chee-ldap-ldap:/var/lib/ldap
      - dcm4chee-ldap-slapdd:/etc/ldap/slapd.d
    restart: always
    networks:
      - pacs_network

    
  arcdb:
    container_name: arcdb
    image: dcm4che/postgres-dcm4chee:12.0-19
    logging:
      driver: json-file
      options:
        max-size: "10m"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dcm4chee-db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - pacs_network
    
  arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.19.0
    #image: mydcm4chee
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 arcdb:5432
      POSTGRES_HOST: arcdb
    logging:
      driver: json-file
      options:
        max-size: "10m"
    depends_on:
      - ldap
      - arcdb
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - dcm4chee-arc-data:/storage
    networks:
      - pacs_network


  db:
    container_name: db
    image: osirixfoundation/kheops-database:${KHEOPS_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    env_file: docker-compose.env
    secrets:
      - kheops_authdb_pass
    restart: on-failure
    networks:
      - kheops_network

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=UTC"
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8089"
    ports:
      - "8089:8089"
    depends_on:
      - db
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_keycloak_password
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "kibana.kheops.online:10.5.5.31"
      - "reportprovider.kheops.online:10.5.5.33"
    networks:
      - kheops_network

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret
    networks:
      - kheops_network


  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - elastic_cloud_id
      - elastic_cloud_auth
    networks:
      - frontend_network


  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=Europe/Zurich"
#      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8089"
    ports:
      - "8049:8080"
#      - "8089:8089"
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network


  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
      - "8042:8042"
      - "8048:8048"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network
      - frontend_network

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "82:80"
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    extra_hosts:
      - "kibana.kheops.online:10.5.5.31"
    networks:
      - kheops_network
      - pacs_network

secrets:
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  OAuth2_secret:
    file: ${SECRETS_PATH}/OAuth2_secret
  kheops_keycloak_clientsecret:
    file: ${SECRETS_PATH}/kheops_keycloak_clientsecret
  kheops_keycloak_password:
    file: ${SECRETS_PATH}/kheops_keycloak_password
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  elastic_cloud_id:
    file: ${SECRETS_PATH}/elastic_cloud_id
  elastic_cloud_auth:
    file: ${SECRETS_PATH}/elastic_cloud_auth
  elastic_pwd:
    file: ${SECRETS_PATH}/elastic_pwd 
  kheops_metric_ressource_password:
    file: ${SECRETS_PATH}/kheops_metric_ressource_password

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  dcm4chee-arc-data:
  kheops-db-data:

networks:
  kheops_network:
    driver: bridge
  pacs_network:
    driver: bridge
  frontend_network:
    driver: bridge

