version: '3.1'

services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:2.4.48-19.1
    env_file: docker-compose.env
    volumes:
      - dcm4chee-ldap-ldap:/var/lib/ldap
      - dcm4chee-ldap-slapdd:/etc/ldap/slapd.d
    restart: on-failure

  arc:
    container_name: pacsarc
    image: osirixfoundation/kheops-dcm4chee-arc-psql:${KHEOPS_ARC_IMAGE_TAG}
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
    volumes:
      - dcm4chee-arc-standalone:/opt/wildfly/standalone
      - /medirad12_archive:/storage
    restart: on-failure

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:v0.9.4
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=UTC"
    depends_on:
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password
    extra_hosts:
      - "keycloak.kheops.online:10.5.5.29"
      - "kibana.kheops.online:10.5.7.8"
      - "reportprovider.kheops.online:10.5.5.33"

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:v0.9.4
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:v0.9.4
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:v0.9.4
    restart: on-failure
    env_file: docker-compose.env
    environment:
      - CATALINA_OPTS="-Duser.timezone=Europe/Zurich"
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret
    extra_hosts:
      - "kibana.kheops.online:10.5.7.8"

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:v0.9.4-letsencrypt
    container_name: kheopsreverseproxy
    env_file: docker-compose.env
    volumes:
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"
      - "kibana.kheops.online:10.5.7.8"

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:v0.9.4
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post
    extra_hosts:
      - "kibana.kheops.online:10.5.7.8"

secrets:
  kheops_authdb_pass:
    file: secrets/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: secrets/kheops_pacsdb_pass
  kheops_superuser_hmasecret:
    file: secrets/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: secrets/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: secrets/kheops_auth_hmasecret_post
  kheops_client_dicomwebproxysecret:
    file: secrets/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: secrets/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: secrets/kheops_metric_ressource_password

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-arc-standalone:
  letsencrypt:
