name: CI Test

on:
  push:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Run1
        run: |
          chmod +x script_run_docker.sh
          ./script_run_docker.sh
          chmod +x script_edit_postman_json.sh
          ./script_edit_postman_json.sh
     # - name: Run2
     #   run: ./script_run_docker.sh
     # - name: Run1.1
     #   run: c
     # - name: Run2.1
     #   run: ./script_edit_postman_json.sh

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        
      - name: install newman
        run: npm install newman@3.10.0
        
      - name: register user
        run: node_modules/.bin/newman run postman/kheops-Get_tokens.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json --export-globals postman/Workspace.postman_globals.json
      
      #- name: register user
      #  uses: matt-ball/newman-action@v0.2.3
      #  with:
      #    collection: postman/kheops-Get_tokens.json
      #    environment: postman/kheops_localhost.postman_environment.json
      #    globals: postman/Workspace.postman_globals.json
      #    export-globals: postman/Workspace.postman_globals.json
      #    export-environment : postman/Workspace.postman_globals.json

      #- name: test1
      #  uses: matt-ball/newman-action@v0.2.3
      #  with:
      #    collection: postman/kheops-DICOMweb_Capability_Tokens.json
      #    environment: postman/kheops_localhost.postman_environment.json
      #    globals: postman/Workspace.postman_globals.json
        

